/*
 * Class name: FractionCalculator
 * Purpose: A GUI class, a fraction calculator with multiple functionalities.
 * Coder: Agnita Paul
 * Date: 6 August 2021
 */

//importing the needed packages here.
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class FractionCalculator extends JFrame {

    //declaring my UI Elements here as class variables or properties.
    private JLabel column_1_label, column_2_label, column_3_label, column_4_label, num_label, den_label;
    private JPanel column_1_panel, column_2_panel, column_3_panel, column_4_panel;
    private JTextField num_textField, den_textField;
    private JButton build_btn, clear_btn;
    private JComboBox<String> operation_comboBox;
    private JList fraction_list, operation_list;

    //declaring my data models here of type Fraction (Build model -- data's stored here when you click on the build button)
    // and of type String (operated data is stored in this model).
    private DefaultListModel<Fraction> fraction_Build_Model = new DefaultListModel<Fraction>();
    private DefaultListModel<String> fraction_Operation_Model = new DefaultListModel<String>();

    //array list to store my fractions once i build them.
    private ArrayList<Fraction> fractionsArrayList = new ArrayList<Fraction>();


    public FractionCalculator() {

        //setting window title
        super("Fraction Calculator");

        //boiler-plate code
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(700,500);
        this.setLocationRelativeTo(null);
        this.setLayout(new GridLayout(1,4));



        //init JLabels
        column_1_label = new JLabel("Enter a Fraction:");
        column_2_label = new JLabel("Here is your fraction:");
        column_3_label = new JLabel("Select an operation:");
        column_4_label = new JLabel("Here is your operation:");
        num_label = new JLabel("Numerator");
        den_label = new JLabel("Denominator");

        //init JTextFields here
        num_textField = new JTextField();
        den_textField = new JTextField();

        //init buttons
        build_btn = new JButton("Build Fraction");
        clear_btn = new JButton("Start Over");

        //init JComboBox
        String[] options = {"Decimal", "Reciprocal", "Fraction1 + Fraction2", "Fraction1 x Fraction2", "Is Fraction1 = Fraction2",
                "Is Fraction1 > Fraction2", "Lowest Terms", "Sort List"};
        //adding options to my combo box
        operation_comboBox = new JComboBox<String>(options);

        //init JLists
        fraction_list = new JList();
        operation_list = new JList();

        //init JPanels here, set it's layout and add appropriate UI Elements to each panel.
        column_1_panel = new JPanel();
        column_1_panel.setLayout(new GridLayout(7,1));
        column_1_panel.add(column_1_label);
        column_1_panel.add(num_label);
        column_1_panel.add(num_textField);
        column_1_panel.add(den_label);
        column_1_panel.add(den_textField);
        column_1_panel.add(build_btn);
        column_1_panel.add(clear_btn);

        column_2_panel = new JPanel();
        column_2_panel.setLayout(new GridLayout(3,1, 0, 0));
        column_2_panel.add(column_2_label);
        column_2_panel.add(fraction_list);

        column_3_panel = new JPanel();
        column_3_panel.setLayout(new GridLayout(3,1));
        column_3_panel.add(column_3_label);
        column_3_panel.add(operation_comboBox);

        column_4_panel = new JPanel();
        column_4_panel.setLayout(new GridLayout(3,1));
        column_4_panel.add(column_4_label);
        column_4_panel.add(operation_list);

        //register my listeners
        build_btn.addActionListener(new Build_Operation());
        operation_comboBox.addActionListener(new Decimal_Operation());
        clear_btn.addActionListener(new Clear_Operation());

        //adding JPanels to my GUI
        this.add(column_1_panel);
        this.add(column_2_panel);
        this.add(column_3_panel);
        this.add(column_4_panel);

        //set my JFrame/Window to be visible
        this.setVisible(true);

    }

    /*
     * Class name: Decimal_Operation
     * Purpose: A private inner class that implements ActionListener Interface
     * Coder: Agnita Paul
     * Date: 6 August 2021
     */
    private class Decimal_Operation implements ActionListener {

        /*
         * Method name:     actionPerformed()
         * Coded by:        Agnita Paul
         * Purpose:         catch the action event generated by the UI Element and perform a specific functionality based on what UI Element triggered that Action event.
         * @pram:           ActionEvent
         * @return:         Void
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            //get Action event generated from a selected combo box option
            String selected = (String) operation_comboBox.getSelectedItem();

            //create an object of last and second last fraction stored in your array list.
            Fraction fraction_1 = fractionsArrayList.get(fractionsArrayList.size() -1); //last element
            Fraction fraction_2 = new Fraction();

            //only create the second object if the size of your array list is greater than 1 to avoid a crash
            if(fractionsArrayList.size() > 1) {
                fraction_2 = fractionsArrayList.get(fractionsArrayList.size() - 2); //2nd last element
            }

            //perform functionality based on the option selected
            if(selected == "Decimal") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_1.toDouble()));
            }
            if(selected == "Reciprocal") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_1.toReciprocal()));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Fraction1 + Fraction2") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_2.add(fraction_1)));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Fraction1 x Fraction2") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_2.multiply(fraction_1)));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Is Fraction1 = Fraction2") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_2.equals(fraction_1)));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Is Fraction1 > Fraction2") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_2.greaterThan(fraction_1)));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Lowest Terms") {
                fraction_Operation_Model.addElement(String.valueOf(fraction_1.lowestTerms()));
                operation_comboBox.setSelectedIndex(0);
            }
            if(selected == "Sort List") {

            }

            operation_list.setModel(fraction_Operation_Model);
        }
    }


    /*
     * Class name: Decimal_Operation
     * Purpose: A private inner class that implements ActionListener Interface
     * Coder: Agnita Paul
     * Date: 6 August 2021
     */
    private class Build_Operation implements ActionListener {

        /*
         * Method name:     actionPerformed()
         * Coded by:        Agnita Paul
         * Purpose:         catch the action event generated by the UI Element and perform a specific functionality based on what UI Element triggered that Action event.
         * @pram:           ActionEvent
         * @return:         Void
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getActionCommand().equals("Build Fraction")) {
                //create a new fractional object, pass in the values from textfield
                Fraction newFraction = new Fraction(Integer.parseInt(num_textField.getText()), Integer.parseInt(den_textField.getText()));
                fractionsArrayList.add(newFraction); //add your object to an array list
                fraction_Build_Model.addElement(newFraction); //add your object to appropriate data model
            }

            fraction_list.setModel(fraction_Build_Model);

            System.out.println(fraction_Build_Model);

            num_textField.setText(null);
            den_textField.setText(null);
        }
    }

    /*
     * Class name: Decimal_Operation
     * Purpose: A private inner class that implements ActionListener Interface
     * Coder: Agnita Paul
     * Date: 6 August 2021
     */
    private class Clear_Operation implements ActionListener {

        /*
         * Method name:     actionPerformed()
         * Coded by:        Agnita Paul
         * Purpose:         catch the action event generated by the UI Element and perform a specific functionality based on what UI Element triggered that Action event.
         * @pram:           ActionEvent
         * @return:         Void
         */
        @Override
        public void actionPerformed(ActionEvent e) {
            //clear textfields, arraylist and models
            num_textField.setText(null);
            den_textField.setText(null);

            fractionsArrayList.clear();
            fraction_Build_Model.clear();
            fraction_Operation_Model.clear();

        }
    }

    /*
     * Method name:     main()
     * Coded by:        Agnita Paul
     * Purpose:         The program runs in the main method
     * @pram:           String[]
     * @return:         Void
     */
    public static void main(String[] args) {
        new FractionCalculator(); //create an anonymous instance of your GUI class.
    }
}
